-- MySQL Script generated by MySQL Workbench
-- Sat Aug 10 08:10:03 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema GESTIONPERSONASLOAIZA
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema GESTIONPERSONASLOAIZA
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `GESTIONPERSONASLOAIZA` ;
-- -----------------------------------------------------
-- Schema gestionpersonasloaiza
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gestionpersonasloaiza
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gestionpersonasloaiza` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `GESTIONPERSONASLOAIZA` ;

-- -----------------------------------------------------
-- Table `GESTIONPERSONASLOAIZA`.`ESTRUCTURA_ORGANIZACIONAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GESTIONPERSONASLOAIZA`.`ESTRUCTURA_ORGANIZACIONAL` (
  `id_estructura` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `id_area` INT NULL DEFAULT NULL,
  `area` VARCHAR(60) NULL DEFAULT NULL,
  `id_subgerencia` INT NULL DEFAULT NULL,
  `subgerencia` VARCHAR(60) NULL DEFAULT NULL,
  `id_gerencia` INT NULL DEFAULT NULL,
  `gerencia` VARCHAR(60) NOT NULL,
  `id_filial` INT NOT NULL,
  `filial` ENUM('A', 'B', 'C') NOT NULL,
  PRIMARY KEY (`id_estructura`));


-- -----------------------------------------------------
-- Table `GESTIONPERSONASLOAIZA`.`CARGOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GESTIONPERSONASLOAIZA`.`CARGOS` (
  `codigo_cargo` INT NOT NULL,
  `cargo` VARCHAR(60) NOT NULL,
  `id_estructura` INT NOT NULL,
  `rol` ENUM('GENERAL', 'PRIVADO') NOT NULL,
  `familia_cargo` VARCHAR(60) NULL DEFAULT NULL,
  `nivel_cargo` INT(2) NULL DEFAULT NULL,
  `personas_a_cargo` ENUM('SI', 'NO') NOT NULL,
  `cargo_comercial` ENUM('SI', 'NO') NULL DEFAULT NULL,
  `region_comercial` VARCHAR(60) NULL DEFAULT NULL,
  PRIMARY KEY (`codigo_cargo`),
  INDEX `FK_CARGOS_ESTRUCTURA` (`id_estructura` ASC) VISIBLE,
  CONSTRAINT `FK_CARGOS_ESTRUCTURA`
    FOREIGN KEY (`id_estructura`)
    REFERENCES `GESTIONPERSONASLOAIZA`.`ESTRUCTURA_ORGANIZACIONAL` (`id_estructura`));


-- -----------------------------------------------------
-- Table `GESTIONPERSONASLOAIZA`.`COLABORADORES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GESTIONPERSONASLOAIZA`.`COLABORADORES` (
  `id_colaborador` VARCHAR(12) NULL DEFAULT NULL,
  `nombres_colaborador` VARCHAR(60) NOT NULL,
  `apellidos_colaborador` VARCHAR(60) NOT NULL,
  `fecha_de_nacimiento` DATE NOT NULL,
  `sexo` ENUM('F', 'M') NOT NULL,
  `fecha_ingreso` DATE NOT NULL,
  `email_colaborador` VARCHAR(30) NOT NULL,
  `direccion_colaborador` VARCHAR(60) NULL DEFAULT NULL,
  `telefono_colaborador` VARCHAR(15) NULL DEFAULT NULL,
  `codigo_cargo` INT NULL DEFAULT NULL,
  `id_jefatura` VARCHAR(12) NULL DEFAULT NULL,
  `sucursal` VARCHAR(30) NOT NULL,
  `id_estructura` INT NOT NULL,
  `nivel_jerarquico` ENUM('AREA', 'SUBGERENCIA', 'GERENCIA') NOT NULL,
  `tipo_contrato` ENUM('PLAZO_FIJO', 'INDEFINIDO') NOT NULL,
  `plazo_contrato` INT NOT NULL,
  `modalidad_jornada` ENUM('PRESENCIAL', 'TELETRABAJO_PARCIAL', 'TELETRABAJO_TOTAL') NULL DEFAULT NULL,
  `nivel_academico` ENUM('ENSEÑANZA_MEDIA', 'TECNICO', 'UNIVERSITARIO', 'ESTUDIOS_SUPERIORES', 'MAGISTER') NOT NULL,
  `cant_hijos` INT NULL DEFAULT NULL,
  `estado_civil` ENUM('SOLTERO/A', 'CASADO/A', 'VIUDO', 'CONVIVIENTE_CIVIL', 'DIVORCIADO/A', 'SEPARADO/A') NULL DEFAULT NULL,
  PRIMARY KEY (`id_colaborador`),
  INDEX `FK_COLABORADOR_ESTRUCTURA_ORGANIZACIONAL` (`id_estructura` ASC) VISIBLE,
  INDEX `FK_COLABORADOR_CARGOS` (`codigo_cargo` ASC) VISIBLE,
  CONSTRAINT `FK_COLABORADOR_ESTRUCTURA_ORGANIZACIONAL`
    FOREIGN KEY (`id_estructura`)
    REFERENCES `GESTIONPERSONASLOAIZA`.`ESTRUCTURA_ORGANIZACIONAL` (`id_estructura`),
  CONSTRAINT `FK_COLABORADOR_CARGOS`
    FOREIGN KEY (`codigo_cargo`)
    REFERENCES `GESTIONPERSONASLOAIZA`.`CARGOS` (`codigo_cargo`));


-- -----------------------------------------------------
-- Table `GESTIONPERSONASLOAIZA`.`CAPACITACIONES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GESTIONPERSONASLOAIZA`.`CAPACITACIONES` (
  `id_capacitacion` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `nombre_capacitacion` VARCHAR(80) NOT NULL,
  `dirigido_a` VARCHAR(150) NULL DEFAULT NULL,
  `hrs_capacitacion` DECIMAL(3,1) NULL DEFAULT NULL,
  `tipo_capacitacion` ENUM('INTERNA', 'EXTERNA') NULL DEFAULT NULL,
  `tipo_malla` ENUM('NORMATIVA', 'TRANSVERSAL', 'VENTA_Y_SERVICIO_AL_CLIENTE', 'DEI', 'TECNICA', 'LIDERAZGO') NULL DEFAULT NULL,
  `plataforma` ENUM('PORTAL_FORMACION_LH', 'PORTAL_ACHS', 'TEAMS', 'OTRA') NULL DEFAULT NULL,
  `nombre_institucion` VARCHAR(60) NULL DEFAULT NULL,
  PRIMARY KEY (`id_capacitacion`));


-- -----------------------------------------------------
-- Table `GESTIONPERSONASLOAIZA`.`CAPACITACIONES_CARGOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GESTIONPERSONASLOAIZA`.`CAPACITACIONES_CARGOS` (
  `id_capacitacion` INT NULL DEFAULT NULL,
  `codigo_cargo` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_capacitacion`, `codigo_cargo`),
  INDEX `FK_CAPACITACIONES_CARGOS_CARGOS` (`codigo_cargo` ASC) VISIBLE,
  CONSTRAINT `FK_CAPACITACIONES_CARGOS_CAPACITACIONES`
    FOREIGN KEY (`id_capacitacion`)
    REFERENCES `GESTIONPERSONASLOAIZA`.`CAPACITACIONES` (`id_capacitacion`),
  CONSTRAINT `FK_CAPACITACIONES_CARGOS_CARGOS`
    FOREIGN KEY (`codigo_cargo`)
    REFERENCES `GESTIONPERSONASLOAIZA`.`CARGOS` (`codigo_cargo`));


-- -----------------------------------------------------
-- Table `GESTIONPERSONASLOAIZA`.`REGISTRO_CAPACITACIONES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GESTIONPERSONASLOAIZA`.`REGISTRO_CAPACITACIONES` (
  `id_capacitacion` INT NOT NULL,
  `id_colaborador` VARCHAR(12) NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  `estado` ENUM('APROBADO', 'REPROBADO', 'NO_REALIZADO') NULL DEFAULT NULL,
  `numero_llamado` INT NULL DEFAULT NULL,
  `observaciones` VARCHAR(200) NULL DEFAULT NULL,
  INDEX `FK_COLABORADOR_REGISTRO_CAPACITACIONES` (`id_colaborador` ASC) VISIBLE,
  INDEX `FK_CAPACITACION_REGISTRO_CAPACITACIONES` (`id_capacitacion` ASC) VISIBLE,
  CONSTRAINT `FK_COLABORADOR_REGISTRO_CAPACITACIONES`
    FOREIGN KEY (`id_colaborador`)
    REFERENCES `GESTIONPERSONASLOAIZA`.`COLABORADORES` (`id_colaborador`),
  CONSTRAINT `FK_CAPACITACION_REGISTRO_CAPACITACIONES`
    FOREIGN KEY (`id_capacitacion`)
    REFERENCES `GESTIONPERSONASLOAIZA`.`CAPACITACIONES` (`id_capacitacion`));


-- -----------------------------------------------------
-- Table `GESTIONPERSONASLOAIZA`.`DESEMPENO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GESTIONPERSONASLOAIZA`.`DESEMPENO` (
  `id_desempeno` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `id_colaborador` VARCHAR(12) NOT NULL,
  `periodo_evaluacion` DATE NOT NULL,
  `calificacion_desempeno` DECIMAL(5,2) NOT NULL,
  `categoria_desempeno` ENUM('BAJO_DESEMPENO', 'NECESIDADES_DE_MEJORA', 'TRABAJO_BIEN_HECHO', 'DESEMPENO_DESTACADO') NULL DEFAULT NULL,
  `conformidad_colaborador` ENUM('SI', 'NO') NULL DEFAULT NULL,
  `evaluacion_publicada` ENUM('SI', 'NO') NULL DEFAULT NULL,
  `plan_de_mejora` ENUM('SI', 'NO') NULL DEFAULT NULL,
  `observaciones` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id_desempeno`),
  INDEX `FK_COLABORADOR_DESEMPENO` (`id_colaborador` ASC) VISIBLE,
  CONSTRAINT `FK_COLABORADOR_DESEMPENO`
    FOREIGN KEY (`id_colaborador`)
    REFERENCES `GESTIONPERSONASLOAIZA`.`COLABORADORES` (`id_colaborador`));


-- -----------------------------------------------------
-- Table `GESTIONPERSONASLOAIZA`.`VACANTES_INTERNAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GESTIONPERSONASLOAIZA`.`VACANTES_INTERNAS` (
  `id_proceso` INT NULL DEFAULT NULL,
  `codigo_cargo` INT NOT NULL,
  `tipo_movilidad` ENUM('MOVILIDAD_DIRIGIDA', 'CONCURSO') NULL DEFAULT NULL,
  `fecha_apertura` DATE NULL DEFAULT NULL,
  `fecha_publicacion` DATE NULL DEFAULT NULL,
  `fecha_cierre` DATE NULL DEFAULT NULL,
  `estado` ENUM('VIGENTE', 'CERRADA') NULL DEFAULT NULL,
  PRIMARY KEY (`id_proceso`));


-- -----------------------------------------------------
-- Table `GESTIONPERSONASLOAIZA`.`POSTULACIONES_MOVILIDADES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GESTIONPERSONASLOAIZA`.`POSTULACIONES_MOVILIDADES` (
  `id_postulacion` INT NULL DEFAULT NULL,
  `id_proceso` INT NOT NULL,
  `id_colaborador` VARCHAR(12) NOT NULL,
  `fecha_postulacion` DATE NULL DEFAULT NULL,
  `direccion_movimiento` ENUM('VERTICAL', 'HORIZONTAL') NULL DEFAULT NULL,
  `ultima_etapa` ENUM('FILTRO_REQUISITOS', 'EVALUACION', 'FINALISTA', 'SELECCIONADO/A') NOT NULL,
  PRIMARY KEY (`id_postulacion`),
  INDEX `FK_COLABORADOR_POSTULACIONES_MOVILIDADES` (`id_colaborador` ASC) VISIBLE,
  INDEX `FK_VACANTES_INTERNAS_POSTULACIONES_MOVILIDADES` (`id_proceso` ASC) VISIBLE,
  CONSTRAINT `FK_COLABORADOR_POSTULACIONES_MOVILIDADES`
    FOREIGN KEY (`id_colaborador`)
    REFERENCES `GESTIONPERSONASLOAIZA`.`COLABORADORES` (`id_colaborador`),
  CONSTRAINT `FK_VACANTES_INTERNAS_POSTULACIONES_MOVILIDADES`
    FOREIGN KEY (`id_proceso`)
    REFERENCES `GESTIONPERSONASLOAIZA`.`VACANTES_INTERNAS` (`id_proceso`));


-- -----------------------------------------------------
-- Table `GESTIONPERSONASLOAIZA`.`DESARROLLO_PROFESIONAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GESTIONPERSONASLOAIZA`.`DESARROLLO_PROFESIONAL` (
  `id_desarrollo` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `id_proceso` INT NULL DEFAULT NULL,
  `id_colaborador` VARCHAR(12) NULL DEFAULT NULL,
  `codigo_cargo_anterior` INT NOT NULL,
  `codigo_nuevo_cargo` INT NOT NULL,
  `fecha_movilidad` DATE NOT NULL,
  `id_postulacion` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_desarrollo`),
  INDEX `FK_COLABORADOR_DESARROLLO` (`id_colaborador` ASC) VISIBLE,
  INDEX `FK_COLABORADOR_POSTULACIONES` (`id_postulacion` ASC) VISIBLE,
  CONSTRAINT `FK_COLABORADOR_DESARROLLO`
    FOREIGN KEY (`id_colaborador`)
    REFERENCES `GESTIONPERSONASLOAIZA`.`COLABORADORES` (`id_colaborador`),
  CONSTRAINT `FK_COLABORADOR_POSTULACIONES`
    FOREIGN KEY (`id_postulacion`)
    REFERENCES `GESTIONPERSONASLOAIZA`.`POSTULACIONES_MOVILIDADES` (`id_postulacion`));


-- -----------------------------------------------------
-- Table `GESTIONPERSONASLOAIZA`.`REGISTRO_BENEFICIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GESTIONPERSONASLOAIZA`.`REGISTRO_BENEFICIOS` (
  `id_beneficio` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `detalle_beneficio` VARCHAR(100) NOT NULL,
  `categoria_beneficio` ENUM('BECA', 'CURSOS_PLAN_GERENCIA') NULL DEFAULT NULL,
  `id_colaborador` VARCHAR(12) NOT NULL,
  `fecha_otorgamiento` DATE NULL DEFAULT NULL,
  `fecha_inicio` DATE NULL DEFAULT NULL,
  `fecha_fin` DATE NULL DEFAULT NULL,
  `resultado` ENUM('EN CURSO', 'APROBADO', 'REPROBADO', 'DESISTE') NULL DEFAULT NULL,
  `observaciones` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id_beneficio`),
  INDEX `FK_REGISTRO_BENEFICIOS_COLABORADORES` (`id_colaborador` ASC) VISIBLE,
  CONSTRAINT `FK_REGISTRO_BENEFICIOS_COLABORADORES`
    FOREIGN KEY (`id_colaborador`)
    REFERENCES `GESTIONPERSONASLOAIZA`.`COLABORADORES` (`id_colaborador`));


-- -----------------------------------------------------
-- Table `GESTIONPERSONASLOAIZA`.`REGISTRO_CAPACITACIONES_MAX_CALIFICACION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GESTIONPERSONASLOAIZA`.`REGISTRO_CAPACITACIONES_MAX_CALIFICACION` (
  `id_capacitacion` INT NOT NULL,
  `id_colaborador` VARCHAR(12) NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  `estado` ENUM('APROBADO', 'REPROBADO', 'NO_REALIZADO') NULL DEFAULT NULL,
  `numero_llamado` INT NULL DEFAULT NULL,
  `observaciones` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id_capacitacion`, `id_colaborador`));

USE `gestionpersonasloaiza` ;

-- -----------------------------------------------------
-- Table `gestionpersonasloaiza`.`bkp_colaboradores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestionpersonasloaiza`.`bkp_colaboradores` (
  `id_colaborador` VARCHAR(12) NOT NULL,
  `nombres_colaborador` VARCHAR(60) NOT NULL,
  `apellidos_colaborador` VARCHAR(60) NOT NULL,
  `fecha_de_nacimiento` DATE NOT NULL,
  `sexo` ENUM('F', 'M') NOT NULL,
  `fecha_ingreso` DATE NOT NULL,
  `email_colaborador` VARCHAR(30) NOT NULL,
  `direccion_colaborador` VARCHAR(60) NULL DEFAULT NULL,
  `telefono_colaborador` VARCHAR(15) NULL DEFAULT NULL,
  `codigo_cargo` INT NULL DEFAULT NULL,
  `id_jefatura` VARCHAR(12) NULL DEFAULT NULL,
  `sucursal` VARCHAR(30) NOT NULL,
  `id_estructura` INT NOT NULL,
  `nivel_jerarquico` ENUM('AREA', 'SUBGERENCIA', 'GERENCIA') NOT NULL,
  `tipo_contrato` ENUM('PLAZO_FIJO', 'INDEFINIDO') NOT NULL,
  `plazo_contrato` INT NOT NULL,
  `modalidad_jornada` ENUM('PRESENCIAL', 'TELETRABAJO_PARCIAL', 'TELETRABAJO_TOTAL') NULL DEFAULT NULL,
  `nivel_academico` ENUM('ENSEÑANZA_MEDIA', 'TECNICO', 'UNIVERSITARIO', 'ESTUDIOS_SUPERIORES', 'MAGISTER') NOT NULL,
  `cant_hijos` INT NULL DEFAULT NULL,
  `estado_civil` ENUM('SOLTERO/A', 'CASADO/A', 'VIUDO', 'CONVIVIENTE_CIVIL', 'DIVORCIADO/A', 'SEPARADO/A') NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gestionpersonasloaiza`.`capacitaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestionpersonasloaiza`.`capacitaciones` (
  `id_capacitacion` INT NOT NULL AUTO_INCREMENT,
  `nombre_capacitacion` VARCHAR(80) NOT NULL,
  `dirigido_a` VARCHAR(150) NULL DEFAULT NULL,
  `hrs_capacitacion` DECIMAL(3,1) NULL DEFAULT NULL,
  `tipo_capacitacion` ENUM('INTERNA', 'EXTERNA') NULL DEFAULT NULL,
  `tipo_malla` ENUM('NORMATIVA', 'TRANSVERSAL', 'VENTA_Y_SERVICIO_AL_CLIENTE', 'DEI', 'TECNICA', 'LIDERAZGO') NULL DEFAULT NULL,
  `plataforma` ENUM('PORTAL_FORMACION_LH', 'PORTAL_ACHS', 'TEAMS', 'OTRA') NULL DEFAULT NULL,
  `nombre_institucion` VARCHAR(60) NULL DEFAULT NULL,
  PRIMARY KEY (`id_capacitacion`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gestionpersonasloaiza`.`estructura_organizacional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestionpersonasloaiza`.`estructura_organizacional` (
  `id_estructura` INT NOT NULL AUTO_INCREMENT,
  `id_area` INT NULL DEFAULT NULL,
  `area` VARCHAR(60) NULL DEFAULT NULL,
  `id_subgerencia` INT NULL DEFAULT NULL,
  `subgerencia` VARCHAR(60) NULL DEFAULT NULL,
  `id_gerencia` INT NULL DEFAULT NULL,
  `gerencia` VARCHAR(60) NOT NULL,
  `id_filial` INT NOT NULL,
  `filial` ENUM('A', 'B', 'C') NOT NULL,
  PRIMARY KEY (`id_estructura`))
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gestionpersonasloaiza`.`cargos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestionpersonasloaiza`.`cargos` (
  `codigo_cargo` INT NOT NULL,
  `cargo` VARCHAR(60) NOT NULL,
  `id_estructura` INT NOT NULL,
  `rol` ENUM('GENERAL', 'PRIVADO') NOT NULL,
  `familia_cargo` VARCHAR(60) NULL DEFAULT NULL,
  `nivel_cargo` INT NULL DEFAULT NULL,
  `personas_a_cargo` ENUM('SI', 'NO') NOT NULL,
  `cargo_comercial` ENUM('SI', 'NO') NULL DEFAULT NULL,
  `region_comercial` VARCHAR(60) NULL DEFAULT NULL,
  PRIMARY KEY (`codigo_cargo`),
  INDEX `FK_CARGOS_ESTRUCTURA` (`id_estructura` ASC) VISIBLE,
  CONSTRAINT `FK_CARGOS_ESTRUCTURA`
    FOREIGN KEY (`id_estructura`)
    REFERENCES `gestionpersonasloaiza`.`estructura_organizacional` (`id_estructura`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gestionpersonasloaiza`.`capacitaciones_cargos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestionpersonasloaiza`.`capacitaciones_cargos` (
  `id_capacitacion` INT NOT NULL,
  `codigo_cargo` INT NOT NULL,
  PRIMARY KEY (`id_capacitacion`, `codigo_cargo`),
  INDEX `FK_CAPACITACIONES_CARGOS_CARGOS` (`codigo_cargo` ASC) VISIBLE,
  CONSTRAINT `FK_CAPACITACIONES_CARGOS_CAPACITACIONES`
    FOREIGN KEY (`id_capacitacion`)
    REFERENCES `gestionpersonasloaiza`.`capacitaciones` (`id_capacitacion`),
  CONSTRAINT `FK_CAPACITACIONES_CARGOS_CARGOS`
    FOREIGN KEY (`codigo_cargo`)
    REFERENCES `gestionpersonasloaiza`.`cargos` (`codigo_cargo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gestionpersonasloaiza`.`colaboradores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestionpersonasloaiza`.`colaboradores` (
  `id_colaborador` VARCHAR(12) NOT NULL,
  `nombres_colaborador` VARCHAR(60) NOT NULL,
  `apellidos_colaborador` VARCHAR(60) NOT NULL,
  `fecha_de_nacimiento` DATE NOT NULL,
  `sexo` ENUM('F', 'M') NOT NULL,
  `fecha_ingreso` DATE NOT NULL,
  `email_colaborador` VARCHAR(30) NOT NULL,
  `direccion_colaborador` VARCHAR(60) NULL DEFAULT NULL,
  `telefono_colaborador` VARCHAR(15) NULL DEFAULT NULL,
  `codigo_cargo` INT NULL DEFAULT NULL,
  `id_jefatura` VARCHAR(12) NULL DEFAULT NULL,
  `sucursal` VARCHAR(30) NOT NULL,
  `id_estructura` INT NOT NULL,
  `nivel_jerarquico` ENUM('AREA', 'SUBGERENCIA', 'GERENCIA') NOT NULL,
  `tipo_contrato` ENUM('PLAZO_FIJO', 'INDEFINIDO') NOT NULL,
  `plazo_contrato` INT NOT NULL,
  `modalidad_jornada` ENUM('PRESENCIAL', 'TELETRABAJO_PARCIAL', 'TELETRABAJO_TOTAL') NULL DEFAULT NULL,
  `nivel_academico` ENUM('ENSEÑANZA_MEDIA', 'TECNICO', 'UNIVERSITARIO', 'ESTUDIOS_SUPERIORES', 'MAGISTER') NOT NULL,
  `cant_hijos` INT NULL DEFAULT NULL,
  `estado_civil` ENUM('SOLTERO/A', 'CASADO/A', 'VIUDO', 'CONVIVIENTE_CIVIL', 'DIVORCIADO/A', 'SEPARADO/A') NULL DEFAULT NULL,
  PRIMARY KEY (`id_colaborador`),
  INDEX `FK_COLABORADOR_ESTRUCTURA_ORGANIZACIONAL` (`id_estructura` ASC) VISIBLE,
  INDEX `FK_COLABORADOR_CARGOS` (`codigo_cargo` ASC) VISIBLE,
  CONSTRAINT `FK_COLABORADOR_CARGOS`
    FOREIGN KEY (`codigo_cargo`)
    REFERENCES `gestionpersonasloaiza`.`cargos` (`codigo_cargo`),
  CONSTRAINT `FK_COLABORADOR_ESTRUCTURA_ORGANIZACIONAL`
    FOREIGN KEY (`id_estructura`)
    REFERENCES `gestionpersonasloaiza`.`estructura_organizacional` (`id_estructura`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gestionpersonasloaiza`.`desempeno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestionpersonasloaiza`.`desempeno` (
  `id_desempeno` INT NOT NULL AUTO_INCREMENT,
  `id_colaborador` VARCHAR(12) NOT NULL,
  `periodo_evaluacion` DATE NOT NULL,
  `calificacion_desempeno` DECIMAL(5,2) NOT NULL,
  `categoria_desempeno` ENUM('BAJO_DESEMPENO', 'NECESIDADES_DE_MEJORA', 'TRABAJO_BIEN_HECHO', 'DESEMPENO_DESTACADO') NULL DEFAULT NULL,
  `conformidad_colaborador` ENUM('SI', 'NO') NULL DEFAULT NULL,
  `evaluacion_publicada` ENUM('SI', 'NO') NULL DEFAULT NULL,
  `plan_de_mejora` ENUM('SI', 'NO') NULL DEFAULT NULL,
  `observaciones` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id_desempeno`),
  INDEX `FK_COLABORADOR_DESEMPENO` (`id_colaborador` ASC) VISIBLE,
  CONSTRAINT `FK_COLABORADOR_DESEMPENO`
    FOREIGN KEY (`id_colaborador`)
    REFERENCES `gestionpersonasloaiza`.`colaboradores` (`id_colaborador`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gestionpersonasloaiza`.`vacantes_internas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestionpersonasloaiza`.`vacantes_internas` (
  `id_proceso` INT NOT NULL,
  `codigo_cargo` INT NOT NULL,
  `tipo_movilidad` ENUM('MOVILIDAD_DIRIGIDA', 'CONCURSO') NULL DEFAULT NULL,
  `fecha_apertura` DATE NULL DEFAULT NULL,
  `fecha_publicacion` DATE NULL DEFAULT NULL,
  `fecha_cierre` DATE NULL DEFAULT NULL,
  `estado` ENUM('VIGENTE', 'CERRADA') NULL DEFAULT NULL,
  PRIMARY KEY (`id_proceso`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gestionpersonasloaiza`.`postulaciones_movilidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestionpersonasloaiza`.`postulaciones_movilidades` (
  `id_postulacion` INT NOT NULL,
  `id_proceso` INT NOT NULL,
  `id_colaborador` VARCHAR(12) NOT NULL,
  `fecha_postulacion` DATE NULL DEFAULT NULL,
  `direccion_movimiento` ENUM('VERTICAL', 'HORIZONTAL') NULL DEFAULT NULL,
  `ultima_etapa` ENUM('FILTRO_REQUISITOS', 'EVALUACION', 'FINALISTA', 'SELECCIONADO/A') NOT NULL,
  PRIMARY KEY (`id_postulacion`),
  INDEX `FK_COLABORADOR_POSTULACIONES_MOVILIDADES` (`id_colaborador` ASC) VISIBLE,
  INDEX `FK_VACANTES_INTERNAS_POSTULACIONES_MOVILIDADES` (`id_proceso` ASC) VISIBLE,
  CONSTRAINT `FK_COLABORADOR_POSTULACIONES_MOVILIDADES`
    FOREIGN KEY (`id_colaborador`)
    REFERENCES `gestionpersonasloaiza`.`colaboradores` (`id_colaborador`),
  CONSTRAINT `FK_VACANTES_INTERNAS_POSTULACIONES_MOVILIDADES`
    FOREIGN KEY (`id_proceso`)
    REFERENCES `gestionpersonasloaiza`.`vacantes_internas` (`id_proceso`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gestionpersonasloaiza`.`registro_beneficios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestionpersonasloaiza`.`registro_beneficios` (
  `id_beneficio` INT NOT NULL AUTO_INCREMENT,
  `detalle_beneficio` VARCHAR(100) NOT NULL,
  `categoria_beneficio` ENUM('BECA', 'CURSOS_PLAN_GERENCIA') NULL DEFAULT NULL,
  `id_colaborador` VARCHAR(12) NOT NULL,
  `fecha_otorgamiento` DATE NULL DEFAULT NULL,
  `fecha_inicio` DATE NULL DEFAULT NULL,
  `fecha_fin` DATE NULL DEFAULT NULL,
  `resultado` ENUM('EN CURSO', 'APROBADO', 'REPROBADO', 'DESISTE') NULL DEFAULT NULL,
  `observaciones` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id_beneficio`),
  INDEX `FK_REGISTRO_BENEFICIOS_COLABORADORES` (`id_colaborador` ASC) VISIBLE,
  CONSTRAINT `FK_REGISTRO_BENEFICIOS_COLABORADORES`
    FOREIGN KEY (`id_colaborador`)
    REFERENCES `gestionpersonasloaiza`.`colaboradores` (`id_colaborador`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gestionpersonasloaiza`.`registro_capacitaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestionpersonasloaiza`.`registro_capacitaciones` (
  `id_capacitacion` INT NOT NULL,
  `id_colaborador` VARCHAR(12) NOT NULL,
  `fecha_inicio` DATE NULL DEFAULT NULL,
  `fecha_fin` DATE NULL DEFAULT NULL,
  `estado` ENUM('APROBADO', 'REPROBADO', 'NO_REALIZADO', 'PENDIENTE INSCRIBIR') NULL DEFAULT NULL,
  `numero_llamado` INT NULL DEFAULT NULL,
  `observaciones` VARCHAR(200) NULL DEFAULT NULL,
  INDEX `FK_COLABORADOR_REGISTRO_CAPACITACIONES` (`id_colaborador` ASC) VISIBLE,
  INDEX `FK_CAPACITACION_REGISTRO_CAPACITACIONES` (`id_capacitacion` ASC) VISIBLE,
  CONSTRAINT `FK_CAPACITACION_REGISTRO_CAPACITACIONES`
    FOREIGN KEY (`id_capacitacion`)
    REFERENCES `gestionpersonasloaiza`.`capacitaciones` (`id_capacitacion`),
  CONSTRAINT `FK_COLABORADOR_REGISTRO_CAPACITACIONES`
    FOREIGN KEY (`id_colaborador`)
    REFERENCES `gestionpersonasloaiza`.`colaboradores` (`id_colaborador`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gestionpersonasloaiza`.`registro_capacitaciones_max_calificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestionpersonasloaiza`.`registro_capacitaciones_max_calificacion` (
  `id_capacitacion` INT NOT NULL,
  `id_colaborador` VARCHAR(12) NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  `estado` ENUM('APROBADO', 'REPROBADO', 'NO_REALIZADO') NULL DEFAULT NULL,
  `numero_llamado` INT NULL DEFAULT NULL,
  `observaciones` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id_capacitacion`, `id_colaborador`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `gestionpersonasloaiza` ;

-- -----------------------------------------------------
-- Placeholder table for view `gestionpersonasloaiza`.`vw_beneficios_colaborador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestionpersonasloaiza`.`vw_beneficios_colaborador` (`id_colaborador` INT, `nombres_colaborador` INT, `apellidos_colaborador` INT, `codigo_cargo` INT, `nombre_cargo` INT, `nombre_gerencia` INT, `id_beneficio` INT, `detalle_beneficio` INT, `categoria_beneficio` INT, `fecha_otorgamiento` INT, `resultado` INT, `observaciones` INT);

-- -----------------------------------------------------
-- Placeholder table for view `gestionpersonasloaiza`.`vw_capacitaciones_por_cargos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestionpersonasloaiza`.`vw_capacitaciones_por_cargos` (`codigo_cargo` INT, `cargo` INT, `id_capacitacion` INT, `nombre_capacitacion` INT);

-- -----------------------------------------------------
-- Placeholder table for view `gestionpersonasloaiza`.`vw_cumplimiento_capacitaciones_normativas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestionpersonasloaiza`.`vw_cumplimiento_capacitaciones_normativas` (`id_colaborador` INT, `ODI_estado` INT, `RIESGO_estado` INT);

-- -----------------------------------------------------
-- Placeholder table for view `gestionpersonasloaiza`.`vw_desempeno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestionpersonasloaiza`.`vw_desempeno` (`id_colaborador` INT, `nombres_colaborador` INT, `apellidos_colaborador` INT, `periodo_evaluacion` INT, `calificacion_desempeno` INT, `categoria_desempeno` INT, `conformidad_colaborador` INT, `evaluacion_publicada` INT, `plan_de_mejora` INT, `observaciones` INT);

-- -----------------------------------------------------
-- Placeholder table for view `gestionpersonasloaiza`.`vw_pendientes_por_inscribir`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestionpersonasloaiza`.`vw_pendientes_por_inscribir` (`id_colaborador` INT, `nombre_capacitacion` INT, `estado` INT);

-- -----------------------------------------------------
-- Placeholder table for view `gestionpersonasloaiza`.`vw_postulaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestionpersonasloaiza`.`vw_postulaciones` (`id_colaborador` INT, `nombres_colaborador` INT, `apellidos_colaborador` INT, `nombre_cargo` INT, `nombre_subgerencia` INT, `nombre_gerencia` INT, `id_proceso` INT, `codigo_cargo` INT, `fecha_cierre` INT, `estado_proceso` INT, `fecha_postulacion` INT, `ultima_etapa` INT);

-- -----------------------------------------------------
-- Placeholder table for view `gestionpersonasloaiza`.`vw_prom_hrs_gcia_por_sex`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestionpersonasloaiza`.`vw_prom_hrs_gcia_por_sex` (`gerencia` INT, `sexo` INT, `promedio_horas` INT);

-- -----------------------------------------------------
-- procedure ExtraerCapacitacionesMaxCalificacion
-- -----------------------------------------------------

DELIMITER $$
USE `gestionpersonasloaiza`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `ExtraerCapacitacionesMaxCalificacion`()
BEGIN
    -- Limpia la tabla de registros con la máxima calificación antes de insertar nuevos registros
    TRUNCATE TABLE REGISTRO_CAPACITACIONES_MAX_CALIFICACION;

    -- Se insertan los registros con la máxima calificación para cada capacitación y colaborador
    INSERT INTO REGISTRO_CAPACITACIONES_MAX_CALIFICACION (id_capacitacion, id_colaborador, fecha_inicio, fecha_fin, estado, numero_llamado, observaciones)
    SELECT 
        r.id_capacitacion, 
        r.id_colaborador, 
        r.fecha_inicio, 
        r.fecha_fin, 
        r.estado, 
        r.numero_llamado, 
        r.observaciones
    FROM 
        REGISTRO_CAPACITACIONES AS r
    INNER JOIN (
        SELECT 
            id_capacitacion, 
            id_colaborador,
            MAX(CASE 
                WHEN estado = 'APROBADO' THEN 3 
                WHEN estado = 'REPROBADO' THEN 2 
                ELSE 1 
            END) AS max_estado
        FROM 
            REGISTRO_CAPACITACIONES
        GROUP BY 
            id_capacitacion, 
            id_colaborador
    ) AS subquery
    ON r.id_capacitacion = subquery.id_capacitacion
    AND r.id_colaborador = subquery.id_colaborador
    AND (CASE 
            WHEN r.estado = 'APROBADO' THEN 3 
            WHEN r.estado = 'REPROBADO' THEN 2 
            ELSE 1 
        END) = subquery.max_estado;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- function get_promedio_horas
-- -----------------------------------------------------

DELIMITER $$
USE `gestionpersonasloaiza`$$
CREATE DEFINER=`root`@`localhost` FUNCTION `get_promedio_horas`(p_id_colaborador VARCHAR(12)) RETURNS decimal(5,2)
    READS SQL DATA
    DETERMINISTIC
BEGIN
    DECLARE promedio DECIMAL(5,2);

    SELECT IFNULL(AVG(c.hrs_capacitacion), 0.00)
    INTO promedio
    FROM REGISTRO_CAPACITACIONES rc
    JOIN CAPACITACIONES c ON rc.id_capacitacion = c.id_capacitacion
    WHERE rc.id_colaborador = p_id_colaborador;

    RETURN promedio;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure obtener_porcentaje_cumplimiento
-- -----------------------------------------------------

DELIMITER $$
USE `gestionpersonasloaiza`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `obtener_porcentaje_cumplimiento`(
    IN fecha_inicio_param DATE,
    IN fecha_fin_param DATE
)
BEGIN
    -- Calcular el porcentaje de cumplimiento de las capacitaciones
    SELECT
        c.id_capacitacion,
        c.nombre_capacitacion,
        COUNT(DISTINCT rc.id_colaborador) AS total_inscritos,
        SUM(CASE WHEN rc.estado = 'APROBADO' THEN 1 ELSE 0 END) AS total_aprobados,
        ROUND(
            (SUM(CASE WHEN rc.estado = 'APROBADO' THEN 1 ELSE 0 END) / 
            COUNT(DISTINCT rc.id_colaborador)) * 100, 
            2
        ) AS porcentaje_cumplimiento
    FROM
        CAPACITACIONES c
    LEFT JOIN
        REGISTRO_CAPACITACIONES rc ON c.id_capacitacion = rc.id_capacitacion
    WHERE
        (rc.fecha_inicio BETWEEN fecha_inicio_param AND fecha_fin_param
        OR rc.fecha_fin BETWEEN fecha_inicio_param AND fecha_fin_param)
    GROUP BY
        c.id_capacitacion, c.nombre_capacitacion;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- function promedio_horas_por_sexo
-- -----------------------------------------------------

DELIMITER $$
USE `gestionpersonasloaiza`$$
CREATE DEFINER=`root`@`localhost` FUNCTION `promedio_horas_por_sexo`(
    sexo_param ENUM('F', 'M'),
    fecha_inicio DATE,
    fecha_fin DATE
) RETURNS decimal(5,1)
    DETERMINISTIC
BEGIN
    DECLARE promedio DECIMAL(5,1);

    SELECT AVG(c.hrs_capacitacion) INTO promedio
    FROM REGISTRO_CAPACITACIONES rc
    JOIN COLABORADORES col ON rc.id_colaborador = col.id_colaborador
    JOIN CAPACITACIONES c ON rc.id_capacitacion = c.id_capacitacion
    WHERE col.sexo = sexo_param
      AND rc.fecha_inicio >= fecha_inicio
      AND rc.fecha_fin <= fecha_fin;
    
    RETURN promedio;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- View `gestionpersonasloaiza`.`vw_beneficios_colaborador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestionpersonasloaiza`.`vw_beneficios_colaborador`;
USE `gestionpersonasloaiza`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `gestionpersonasloaiza`.`vw_beneficios_colaborador` AS select `r`.`id_colaborador` AS `id_colaborador`,`c`.`nombres_colaborador` AS `nombres_colaborador`,`c`.`apellidos_colaborador` AS `apellidos_colaborador`,`c`.`codigo_cargo` AS `codigo_cargo`,`ca`.`cargo` AS `nombre_cargo`,`e`.`gerencia` AS `nombre_gerencia`,`r`.`id_beneficio` AS `id_beneficio`,`r`.`detalle_beneficio` AS `detalle_beneficio`,`r`.`categoria_beneficio` AS `categoria_beneficio`,`r`.`fecha_otorgamiento` AS `fecha_otorgamiento`,`r`.`resultado` AS `resultado`,`r`.`observaciones` AS `observaciones` from (((`gestionpersonasloaiza`.`registro_beneficios` `r` join `gestionpersonasloaiza`.`colaboradores` `c` on((`r`.`id_colaborador` = `c`.`id_colaborador`))) join `gestionpersonasloaiza`.`cargos` `ca` on((`c`.`codigo_cargo` = `ca`.`codigo_cargo`))) join `gestionpersonasloaiza`.`estructura_organizacional` `e` on((`ca`.`id_estructura` = `e`.`id_estructura`)));

-- -----------------------------------------------------
-- View `gestionpersonasloaiza`.`vw_capacitaciones_por_cargos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestionpersonasloaiza`.`vw_capacitaciones_por_cargos`;
USE `gestionpersonasloaiza`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `gestionpersonasloaiza`.`vw_capacitaciones_por_cargos` AS select `c`.`codigo_cargo` AS `codigo_cargo`,`c`.`cargo` AS `cargo`,`cp`.`id_capacitacion` AS `id_capacitacion`,`cp`.`nombre_capacitacion` AS `nombre_capacitacion` from ((`gestionpersonasloaiza`.`cargos` `c` join `gestionpersonasloaiza`.`capacitaciones_cargos` `cc` on((`c`.`codigo_cargo` = `cc`.`codigo_cargo`))) join `gestionpersonasloaiza`.`capacitaciones` `cp` on((`cc`.`id_capacitacion` = `cp`.`id_capacitacion`)));

-- -----------------------------------------------------
-- View `gestionpersonasloaiza`.`vw_cumplimiento_capacitaciones_normativas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestionpersonasloaiza`.`vw_cumplimiento_capacitaciones_normativas`;
USE `gestionpersonasloaiza`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `gestionpersonasloaiza`.`vw_cumplimiento_capacitaciones_normativas` AS select `c`.`id_colaborador` AS `id_colaborador`,max((case when (`cap`.`nombre_capacitacion` = 'ODI') then `rc`.`estado` end)) AS `ODI_estado`,max((case when (`cap`.`nombre_capacitacion` = 'RIESGO') then `rc`.`estado` end)) AS `RIESGO_estado` from ((`gestionpersonasloaiza`.`colaboradores` `c` join `gestionpersonasloaiza`.`registro_capacitaciones` `rc` on((`c`.`id_colaborador` = `rc`.`id_colaborador`))) join `gestionpersonasloaiza`.`capacitaciones` `cap` on((`rc`.`id_capacitacion` = `cap`.`id_capacitacion`))) where (`cap`.`tipo_malla` = 'NORMATIVA') group by `c`.`id_colaborador`;

-- -----------------------------------------------------
-- View `gestionpersonasloaiza`.`vw_desempeno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestionpersonasloaiza`.`vw_desempeno`;
USE `gestionpersonasloaiza`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `gestionpersonasloaiza`.`vw_desempeno` AS select `c`.`id_colaborador` AS `id_colaborador`,`c`.`nombres_colaborador` AS `nombres_colaborador`,`c`.`apellidos_colaborador` AS `apellidos_colaborador`,`e`.`periodo_evaluacion` AS `periodo_evaluacion`,`e`.`calificacion_desempeno` AS `calificacion_desempeno`,`e`.`categoria_desempeno` AS `categoria_desempeno`,`e`.`conformidad_colaborador` AS `conformidad_colaborador`,`e`.`evaluacion_publicada` AS `evaluacion_publicada`,`e`.`plan_de_mejora` AS `plan_de_mejora`,`e`.`observaciones` AS `observaciones` from (`gestionpersonasloaiza`.`colaboradores` `c` left join `gestionpersonasloaiza`.`desempeno` `e` on((`c`.`id_colaborador` = `e`.`id_colaborador`)));

-- -----------------------------------------------------
-- View `gestionpersonasloaiza`.`vw_pendientes_por_inscribir`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestionpersonasloaiza`.`vw_pendientes_por_inscribir`;
USE `gestionpersonasloaiza`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `gestionpersonasloaiza`.`vw_pendientes_por_inscribir` AS select `rc`.`id_colaborador` AS `id_colaborador`,`c`.`nombre_capacitacion` AS `nombre_capacitacion`,`rc`.`estado` AS `estado` from (`gestionpersonasloaiza`.`registro_capacitaciones` `rc` join `gestionpersonasloaiza`.`capacitaciones` `c` on((`rc`.`id_capacitacion` = `c`.`id_capacitacion`))) where (`rc`.`estado` = 'PENDIENTE INSCRIBIR');

-- -----------------------------------------------------
-- View `gestionpersonasloaiza`.`vw_postulaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestionpersonasloaiza`.`vw_postulaciones`;
USE `gestionpersonasloaiza`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `gestionpersonasloaiza`.`vw_postulaciones` AS select `p`.`id_colaborador` AS `id_colaborador`,`c`.`nombres_colaborador` AS `nombres_colaborador`,`c`.`apellidos_colaborador` AS `apellidos_colaborador`,`car`.`cargo` AS `nombre_cargo`,`e`.`subgerencia` AS `nombre_subgerencia`,`e`.`gerencia` AS `nombre_gerencia`,`v`.`id_proceso` AS `id_proceso`,`v`.`codigo_cargo` AS `codigo_cargo`,`v`.`fecha_cierre` AS `fecha_cierre`,`v`.`estado` AS `estado_proceso`,`p`.`fecha_postulacion` AS `fecha_postulacion`,`p`.`ultima_etapa` AS `ultima_etapa` from ((((`gestionpersonasloaiza`.`postulaciones_movilidades` `p` join `gestionpersonasloaiza`.`vacantes_internas` `v` on((`p`.`id_proceso` = `v`.`id_proceso`))) join `gestionpersonasloaiza`.`colaboradores` `c` on((`p`.`id_colaborador` = `c`.`id_colaborador`))) join `gestionpersonasloaiza`.`cargos` `car` on((`c`.`codigo_cargo` = `car`.`codigo_cargo`))) join `gestionpersonasloaiza`.`estructura_organizacional` `e` on((`car`.`id_estructura` = `e`.`id_estructura`)));

-- -----------------------------------------------------
-- View `gestionpersonasloaiza`.`vw_prom_hrs_gcia_por_sex`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestionpersonasloaiza`.`vw_prom_hrs_gcia_por_sex`;
USE `gestionpersonasloaiza`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `gestionpersonasloaiza`.`vw_prom_hrs_gcia_por_sex` AS select `e`.`gerencia` AS `gerencia`,`c`.`sexo` AS `sexo`,round(avg(`cp`.`hrs_capacitacion`),1) AS `promedio_horas` from ((((`gestionpersonasloaiza`.`colaboradores` `c` join `gestionpersonasloaiza`.`registro_capacitaciones` `rc` on((`c`.`id_colaborador` = `rc`.`id_colaborador`))) join `gestionpersonasloaiza`.`capacitaciones` `cp` on((`rc`.`id_capacitacion` = `cp`.`id_capacitacion`))) join `gestionpersonasloaiza`.`cargos` `ca` on((`c`.`codigo_cargo` = `ca`.`codigo_cargo`))) join `gestionpersonasloaiza`.`estructura_organizacional` `e` on((`ca`.`id_estructura` = `e`.`id_estructura`))) where (`cp`.`tipo_malla` = 'NORMATIVA') group by `e`.`gerencia`,`c`.`sexo`;
USE `gestionpersonasloaiza`;

DELIMITER $$
USE `gestionpersonasloaiza`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `gestionpersonasloaiza`.`trg_insertar_en_registro_capacitaciones`
AFTER INSERT ON `gestionpersonasloaiza`.`colaboradores`
FOR EACH ROW
BEGIN
    -- Insertar en REGISTRO_CAPACITACIONES todos los cursos correspondientes al cargo del nuevo colaborador
    INSERT INTO REGISTRO_CAPACITACIONES (id_capacitacion, id_colaborador, fecha_inicio, fecha_fin, estado)
    SELECT c.id_capacitacion, NEW.id_colaborador, NULL, NULL, 'PENDIENTE INSCRIBIR'
    FROM CAPACITACIONES_CARGOS cc
    JOIN CAPACITACIONES c ON cc.id_capacitacion = c.id_capacitacion
    WHERE cc.codigo_cargo = NEW.codigo_cargo;
END$$

USE `gestionpersonasloaiza`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `gestionpersonasloaiza`.`trg_eliminar_pendiente_inscribir`
AFTER UPDATE ON `gestionpersonasloaiza`.`registro_capacitaciones`
FOR EACH ROW
BEGIN
    -- Elimina registros de estado 'PENDIENTE INSCRIBIR' cuando se actualiza con una fecha de inicio
    IF NEW.fecha_inicio IS NOT NULL AND OLD.estado = 'PENDIENTE INSCRIBIR' THEN
        DELETE FROM REGISTRO_CAPACITACIONES
        WHERE id_colaborador = OLD.id_colaborador
        AND id_capacitacion = OLD.id_capacitacion
        AND estado = 'PENDIENTE INSCRIBIR';
    END IF;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
